# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: gs-auth-api.endpoints.agones-poc.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Game Server gRPC API
apis:
- name: GameserverAuthentication

#
# API usage restrictions.
#
usage:
  rules:
  # GameserverAuthentication methods can be called without an API Key.
  - selector: GameserverAuthentication.RegisterPlayer
    allow_unregistered_calls: true
  - selector: GameserverAuthentication.LoginPlayer
    allow_unregistered_calls: true
  - selector: GameserverAuthentication.LogoutPlayer
    allow_unregistered_calls: true
  - selector: GameserverAuthentication.GetPlayerInfo
    allow_unregistered_calls: true
  - selector: GameserverAuthentication.AuthenticationTokenRefresh
    allow_unregistered_calls: true
  - selector: GameserverAuthentication.UpdateActivity
    allow_unregistered_calls: true