# Create a Role in the default namespace that grants access to the agones api
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-scaler
  namespace: default
  labels:
    app: fleet-scaler
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["stable.agones.dev"]
  resources: ["fleetautoscalers"]
  verbs: ["update"] 
- apiGroups: ["stable.agones.dev"]
  resources: ["fleetautoscalers"]
  verbs: ["create"]    
- apiGroups: ["stable.agones.dev"]
  resources: ["fleetallocations"]
  verbs: ["create"]
- apiGroups: ["stable.agones.dev"]
  resources: ["fleetautoscalers"]
  verbs: ["get"]   
- apiGroups: ["stable.agones.dev"]
  resources: [fleets, fleet"]
  verbs: ["get"] 
  
  


---
# Create a ServiceAccount that will be bound to the above role
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-scaler
  namespace: default
  labels:
    app: fleet-scaler

---
# Bind the fleet-allocator ServiceAccount to the fleet-allocator Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleet-scaler
  namespace: default
  labels:
    app: fleet-scaler
subjects:
- kind: ServiceAccount
  name: fleet-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-scaler
